# SELECT dpc.CAR_ID, dpc.CAR_TYPE, dpc.THIRTY_DAY_FEE AS FEE
# FROM
# (
#     SELECT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE, dp.DISCOUNT_RATE,
#     FLOOR((1 - dp.DISCOUNT_RATE / 100) * c.DAILY_FEE * 30) AS THIRTY_DAY_FEE
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
#     JOIN CAR_RENTAL_COMPANY_CAR c
#     ON dp.CAR_TYPE = c.CAR_TYPE
#     WHERE (dp.CAR_TYPE = '세단' OR dp.CAR_TYPE = 'SUV') AND dp.DURATION_TYPE = '30일 이상'
# ) dpc
# JOIN
# (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE <= '2022-11-30' OR END_DATE >= '2022-11-01'
# ) h
# ON dpc.CAR_ID = h.CAR_ID
# WHERE 500000 <= dpc.THIRTY_DAY_FEE AND dpc.THIRTY_DAY_FEE < 2000000
# ORDER BY FEE desc, dpc.CAR_TYPE asc, dpc.CAR_ID desc
SELECT
  c.CAR_ID,
  c.CAR_TYPE,
  FLOOR(c.DAILY_FEE * 30 * (100 - dp.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
  ON dp.CAR_TYPE = c.CAR_TYPE
 AND dp.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        WHERE h.CAR_ID = c.CAR_ID
          -- exclude cars with ANY overlap with 2022-11-01 - 2022-11-30
          AND h.START_DATE <= '2022-11-30'
          AND h.END_DATE   >= '2022-11-01'
      )
  AND FLOOR(c.DAILY_FEE * 30 * (100 - dp.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;