WITH u AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)
SELECT 
    YEAR(os.SALES_DATE) AS YEAR, 
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT os.USER_ID) as PURCHASED_USERS,
    ROUND(COUNT(DISTINCT os.USER_ID) / (SELECT COUNT(*) FROM u), 1) AS PURCHASED_RATIO
    
FROM ONLINE_SALE os
JOIN u ON u.USER_ID = os.USER_ID
GROUP BY year(os.SALES_DATE), month(SALES_DATE)
ORDER BY YEAR asc, MONTH asc