WITH RECURSIVE GEN_CTE AS (
    SELECT
        ID,
        PARENT_ID,
    1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL
    
    SELECT
    E.ID,
    E.PARENT_ID,
    G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN_CTE G
    ON E.PARENT_ID = G.ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM GEN_CTE
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM GEN_CTE WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION ASC
;
